package com.funi.demo.mbg.dao;

import com.funi.demo.mbg.dto.LoginRec;
import com.funi.demo.mbg.dto.LoginRecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    long countByExample(LoginRecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int deleteByExample(LoginRecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int insert(LoginRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int insertSelective(LoginRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    List<LoginRec> selectByExample(LoginRecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    LoginRec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") LoginRec record, @Param("example") LoginRecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int updateByExample(@Param("record") LoginRec record, @Param("example") LoginRecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int updateByPrimaryKeySelective(LoginRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    int updateByPrimaryKey(LoginRec record);

	//自定义属性或方法
}