package com.funi.demo.mbg.dto;

import com.funi.demo.supports.BasicDto;
import java.io.Serializable;
import java.util.Date;

public class LoginRec extends BasicDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * serialVersionUID 序列号 
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_rec.id
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_rec.user_id
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_rec.password
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_rec.login_date
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    private Date loginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_rec.login_ip
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_rec.REMARK
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_rec.id
     *
     * @return the value of t_login_rec.id
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_rec.id
     *
     * @param id the value for t_login_rec.id
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_rec.user_id
     *
     * @return the value of t_login_rec.user_id
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_rec.user_id
     *
     * @param userId the value for t_login_rec.user_id
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_rec.password
     *
     * @return the value of t_login_rec.password
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_rec.password
     *
     * @param password the value for t_login_rec.password
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_rec.login_date
     *
     * @return the value of t_login_rec.login_date
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_rec.login_date
     *
     * @param loginDate the value for t_login_rec.login_date
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_rec.login_ip
     *
     * @return the value of t_login_rec.login_ip
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_rec.login_ip
     *
     * @param loginIp the value for t_login_rec.login_ip
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_rec.REMARK
     *
     * @return the value of t_login_rec.REMARK
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_rec.REMARK
     *
     * @param remark the value for t_login_rec.REMARK
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	//自定义属性或方法
}