package com.funi.demo.mbg.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LoginRecExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * serialVersionUID 序列号 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public LoginRecExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andLoginDateIsNull() {
            addCriterion("login_date is null");
            return (Criteria) this;
        }

        public Criteria andLoginDateIsNotNull() {
            addCriterion("login_date is not null");
            return (Criteria) this;
        }

        public Criteria andLoginDateEqualTo(Date value) {
            addCriterionForJDBCDate("login_date =", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("login_date <>", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateGreaterThan(Date value) {
            addCriterionForJDBCDate("login_date >", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("login_date >=", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateLessThan(Date value) {
            addCriterionForJDBCDate("login_date <", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("login_date <=", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateIn(List<Date> values) {
            addCriterionForJDBCDate("login_date in", values, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("login_date not in", values, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("login_date between", value1, value2, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("login_date not between", value1, value2, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginIpIsNull() {
            addCriterion("login_ip is null");
            return (Criteria) this;
        }

        public Criteria andLoginIpIsNotNull() {
            addCriterion("login_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIpEqualTo(String value) {
            addCriterion("login_ip =", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotEqualTo(String value) {
            addCriterion("login_ip <>", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpGreaterThan(String value) {
            addCriterion("login_ip >", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("login_ip >=", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpLessThan(String value) {
            addCriterion("login_ip <", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpLessThanOrEqualTo(String value) {
            addCriterion("login_ip <=", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpLike(String value) {
            addCriterion("login_ip like", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotLike(String value) {
            addCriterion("login_ip not like", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpIn(List<String> values) {
            addCriterion("login_ip in", values, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotIn(List<String> values) {
            addCriterion("login_ip not in", values, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpBetween(String value1, String value2) {
            addCriterion("login_ip between", value1, value2, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotBetween(String value1, String value2) {
            addCriterion("login_ip not between", value1, value2, "loginIp");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Boolean value) {
            addCriterion("IS_DELETED =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Boolean value) {
            addCriterion("IS_DELETED <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Boolean value) {
            addCriterion("IS_DELETED >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_DELETED >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Boolean value) {
            addCriterion("IS_DELETED <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_DELETED <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Boolean> values) {
            addCriterion("IS_DELETED in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Boolean> values) {
            addCriterion("IS_DELETED not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DELETED between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DELETED not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeIsNull() {
            addCriterion("SYS_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeIsNotNull() {
            addCriterion("SYS_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_CREATE_TIME =", value, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_CREATE_TIME <>", value, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("SYS_CREATE_TIME >", value, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_CREATE_TIME >=", value, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("SYS_CREATE_TIME <", value, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_CREATE_TIME <=", value, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("SYS_CREATE_TIME in", values, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("SYS_CREATE_TIME not in", values, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SYS_CREATE_TIME between", value1, value2, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SYS_CREATE_TIME not between", value1, value2, "sysCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeIsNull() {
            addCriterion("SYS_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeIsNotNull() {
            addCriterion("SYS_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME =", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME <>", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME >", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME >=", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME <", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME <=", value, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME in", values, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME not in", values, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME between", value1, value2, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SYS_UPDATE_TIME not between", value1, value2, "sysUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeIsNull() {
            addCriterion("SYS_DELETE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeIsNotNull() {
            addCriterion("SYS_DELETE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_DELETE_TIME =", value, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_DELETE_TIME <>", value, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("SYS_DELETE_TIME >", value, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_DELETE_TIME >=", value, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeLessThan(Date value) {
            addCriterionForJDBCDate("SYS_DELETE_TIME <", value, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SYS_DELETE_TIME <=", value, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeIn(List<Date> values) {
            addCriterionForJDBCDate("SYS_DELETE_TIME in", values, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("SYS_DELETE_TIME not in", values, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SYS_DELETE_TIME between", value1, value2, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysDeleteTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SYS_DELETE_TIME not between", value1, value2, "sysDeleteTime");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdIsNull() {
            addCriterion("SYS_CREATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdIsNotNull() {
            addCriterion("SYS_CREATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdEqualTo(String value) {
            addCriterion("SYS_CREATE_ID =", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdNotEqualTo(String value) {
            addCriterion("SYS_CREATE_ID <>", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdGreaterThan(String value) {
            addCriterion("SYS_CREATE_ID >", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_CREATE_ID >=", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdLessThan(String value) {
            addCriterion("SYS_CREATE_ID <", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdLessThanOrEqualTo(String value) {
            addCriterion("SYS_CREATE_ID <=", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdLike(String value) {
            addCriterion("SYS_CREATE_ID like", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdNotLike(String value) {
            addCriterion("SYS_CREATE_ID not like", value, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdIn(List<String> values) {
            addCriterion("SYS_CREATE_ID in", values, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdNotIn(List<String> values) {
            addCriterion("SYS_CREATE_ID not in", values, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdBetween(String value1, String value2) {
            addCriterion("SYS_CREATE_ID between", value1, value2, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysCreateIdNotBetween(String value1, String value2) {
            addCriterion("SYS_CREATE_ID not between", value1, value2, "sysCreateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdIsNull() {
            addCriterion("SYS_UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdIsNotNull() {
            addCriterion("SYS_UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdEqualTo(String value) {
            addCriterion("SYS_UPDATE_ID =", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdNotEqualTo(String value) {
            addCriterion("SYS_UPDATE_ID <>", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdGreaterThan(String value) {
            addCriterion("SYS_UPDATE_ID >", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_UPDATE_ID >=", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdLessThan(String value) {
            addCriterion("SYS_UPDATE_ID <", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("SYS_UPDATE_ID <=", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdLike(String value) {
            addCriterion("SYS_UPDATE_ID like", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdNotLike(String value) {
            addCriterion("SYS_UPDATE_ID not like", value, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdIn(List<String> values) {
            addCriterion("SYS_UPDATE_ID in", values, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdNotIn(List<String> values) {
            addCriterion("SYS_UPDATE_ID not in", values, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdBetween(String value1, String value2) {
            addCriterion("SYS_UPDATE_ID between", value1, value2, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysUpdateIdNotBetween(String value1, String value2) {
            addCriterion("SYS_UPDATE_ID not between", value1, value2, "sysUpdateId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdIsNull() {
            addCriterion("SYS_DELETE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdIsNotNull() {
            addCriterion("SYS_DELETE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdEqualTo(String value) {
            addCriterion("SYS_DELETE_ID =", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdNotEqualTo(String value) {
            addCriterion("SYS_DELETE_ID <>", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdGreaterThan(String value) {
            addCriterion("SYS_DELETE_ID >", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DELETE_ID >=", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdLessThan(String value) {
            addCriterion("SYS_DELETE_ID <", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdLessThanOrEqualTo(String value) {
            addCriterion("SYS_DELETE_ID <=", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdLike(String value) {
            addCriterion("SYS_DELETE_ID like", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdNotLike(String value) {
            addCriterion("SYS_DELETE_ID not like", value, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdIn(List<String> values) {
            addCriterion("SYS_DELETE_ID in", values, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdNotIn(List<String> values) {
            addCriterion("SYS_DELETE_ID not in", values, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdBetween(String value1, String value2) {
            addCriterion("SYS_DELETE_ID between", value1, value2, "sysDeleteId");
            return (Criteria) this;
        }

        public Criteria andSysDeleteIdNotBetween(String value1, String value2) {
            addCriterion("SYS_DELETE_ID not between", value1, value2, "sysDeleteId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_rec
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 11 08:47:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_rec
     *
     * @mbg.generated Tue Jul 11 08:47:19 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

	//自定义属性或方法
}